import requests
from django.conf import settings
import webbrowser
from django.shortcuts import render
class MyMiddleware(object):

	def __init__(self,get_response):
		self.get_response=get_response

	def __call__(self,request):
		return self.get_response(request)

	def process_exception(self,request,exception):
		#for debugging
		intitle=u'{}:{}'.format(exception.__class__.__name__,str(exception))
		print(intitle,'For debugging')
		#for debugging

		#the webbrowser will open the link on a new window
		#str(excpetion) is the error message generated by the framework 
		webbrowser.open_new("https://www.google.co.in/search?q="+str(exception))
		return None

class mid2(object):
	def __init__(self,get_response):
		self.get_response=get_response

	def __call__(self,request):
		a=self.get_response(request)
		if(a.status_code!=404):
			return a
		else:
			return render(request,'museo/404.html',{}) #if status code is 404 then render this page 